---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update yum cache.
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'
      changed_when: false

  roles:
    - role: node-exporter
